### ISSUE TITLE
功能模块的代码如何获得？

### ISSUE THREAD

**Issue by Jiahe-Sun** [openbiox/hiplot-org-plugins#1]
你好，感谢你们开发了这个强大的可视化工具，我有个疑问：为什么github中许多插件功能的代码没有开源呢？我想利用R代码批量绘图，但是发现源代码库中没有相关的代码，只有这个模块的文档说明，希望得到你的帮助

**Comment by Miachol** [comment]
未开源工具代码需要联系对应工具作者：

lee_jianfeng@sjtu.edu.cn Jianfeng Li
benben.miao@outlook.com Benben Miao
wangshx@shanghaitech.edu.cn Shixiang Wang
dongw26@mail2.sysu.edu.cn Wei Dong
houshi@sjtu.edu.cn Houshi Xu
huzai920621@126.com Mingjie Wang
